PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo_goa: <http://www.semantic-systems-biology.org/ontology/rdf/OBO#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX cheminf: <http://semanticscience.org/resource/>
PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo_goa: <http://www.semantic-systems-biology.org/ontology/rdf/OBO#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX cheminf: <http://semanticscience.org/resource/>
SELECT DISTINCT ?item ?chembl_compound WHERE {
{ SELECT DISTINCT ?chembl_target ?chembl_compound ?ocrs_compound ?node_uri ?assay_uri ?item ?target_type ?issue ?dup ?conf_score WHERE {
 ?chembl_target chembl:hasProteinClassification|chembl:hasTargetComponent/chembl:targetCmptXref|chembl:hasTargetComponent/skos:exactMatch/obo_goa:C|chembl:hasTargetComponent/skos:exactMatch/obo_goa:F|chembl:hasTargetComponent/skos:exactMatch/obo_goa:P ?class .
 VALUES ?node_uri { <http://purl.uniprot.org/enzyme/6.2.-.->  } GRAPH ?g {
 ?class rdfs:subClassOf ?node_uri .
 }
 GRAPH <http://www.ebi.ac.uk/chembl> {
 ?item a chembl:Activity ;
 chembl:hasAssay ?assay_uri ;
 chembl:hasMolecule ?chembl_compound .
 ?assay_uri chembl:hasTarget ?chembl_target .
 ?chembl_target a ?target_type .
 OPTIONAL {
 GRAPH <http://ops.rsc.org> {
 ?ocrs_compound skos:exactMatch ?chembl_compound .
 }
 }
 OPTIONAL { ?item chembl:dataValidityIssue ?issue_tmp }
 BIND (IF (BOUND(?issue_tmp) , true, false) AS ?issue)
 OPTIONAL { ?item chembl:potentialDuplicate ?dup_tmp }
 BIND (IF (BOUND(?dup_tmp) , true, false) AS ?dup)
 OPTIONAL { ?assay_uri chembl:targetConfScore ?conf_score_tmp }
 BIND (IF (BOUND(?conf_score_tmp) , ?conf_score_tmp, 0) AS ?conf_score)
 }
} }
GRAPH <http://www.ebi.ac.uk/chembl> {
 { ?assay_uri chembl:organismName ?assay_organism }
 UNION { ?assay_uri dcterms:description ?assay_description }
 UNION { ?assay_uri chembl:assayTestType ?assay_type }
 UNION { ?assay_uri chembl:targetConfDesc ?conf_desc }
 UNION { ?assay_uri chembl:targetRelType ?rel_type ;
 chembl:targetRelDesc ?rel_desc }
 UNION { ?chembl_target dcterms:title ?target_name }
 UNION { ?chembl_target chembl:organismName ?target_organism }
 UNION { ?chembl_target chembl:hasTargetComponent ?protein .
 OPTIONAL {
 GRAPH <http://www.conceptwiki.org> {
 ?cw_target skos:exactMatch ?protein ;
 skos:prefLabel ?protein_name
 }
 }
 }
 UNION { ?item chembl:publishedType ?published_type }
 UNION { ?item chembl:publishedRelation ?published_relation }
 UNION { ?item chembl:publishedValue ?published_value }
 UNION { ?item chembl:publishedUnits ?published_unit }
 UNION { ?item chembl:standardType ?activity_type }
 UNION { ?item chembl:standardRelation ?activity_relation }
 UNION { ?item chembl:standardValue ?std_value .
 BIND (xsd:decimal(?std_value) as ?activity_value)
 }
 UNION { ?item chembl:standardUnits ?activity_unit }
 UNION { ?item chembl:hasQUDT ?qudt_uri }
 UNION { ?item chembl:pChembl ?pChembl }
 UNION { ?item chembl:activityComment ?act_comment }
 UNION { ?item chembl:hasDocument ?document .
 { ?document owl:sameAs ?doi }
 UNION { ?document bibo:pmid ?pmid }
 }
 UNION { ?item chembl:dataValidityComment ?comment}  UNION {
 GRAPH <http://ops.rsc.org> {
 { ?ocrs_compound cheminf:CHEMINF_000396 ?inchi }
 UNION {?ocrs_compound cheminf:CHEMINF_000399 ?inchi_key}
 UNION {?ocrs_compound cheminf:CHEMINF_000018 ?smiles }
 }
 }
}
 } ORDER BY ?item  LIMIT 10 OFFSET 0
 
