PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?item  WHERE {  VALUES ?uniprot_target_uri { <http://purl.uniprot.org/uniprot/Q9Y5Y9>  } GRAPH <http://purl.uniprot.org> {
 ?uniprot_target_uri uniprot:existence ?existence .
}
 VALUES ?dg_gene_uri { <http://identifiers.org/ncbigene/6336>  } GRAPH <http://rdf.imim.es> {
 ?item sio:SIO_000628 ?dg_gene_uri .
 ?dg_gene_uri rdf:type ncit:C16612 ;
 void:inDataset ?geneDataset .  ?item rdf:type ?type .
 ?type rdfs:label ?type_label .  ?item sio:SIO_000253 ?primarySource .
 ?item sio:SIO_000628 ?disease .
 ?disease rdf:type ncit:C7057 ;
 foaf:name ?diseaseName ;
 void:inDataset ?diseaseDataset .
 ?item void:inDataset ?assocDataset .
 OPTIONAL { ?disease sio:SIO_000095 ?diseaseClass .
 ?diseaseClass foaf:name ?diseaseClassName ;
 void:inDataset ?diseaseClassDataset .
 }
 OPTIONAL { ?item dcterms:description ?description .}
 OPTIONAL { ?item sio:SIO_000772 ?pubmed_id . }
}
OPTIONAL {  VALUES ?cw_target_uri { <http://www.conceptwiki.org/concept/index/00059958-a045-4581-9dc5-e5a08bb0c291> <http://www.conceptwiki.org/concept/00059958-a045-4581-9dc5-e5a08bb0c291>  } GRAPH <http://www.conceptwiki.org> {
 ?cw_target_uri skos:prefLabel ?cw_prefLabel .
}} } ORDER BY ?item  LIMIT 10 OFFSET 0



